{
    "id": "6HNRlExjQcisy1iZVwl8EA",
    "first_name": "350",
    "last_name": "Webinars",
    "email": "webinars@350.org",
    "type": 2,
    "role_name": "Member",
    "pmi": 3411071981,
    "use_pmi": false,
    "personal_meeting_url": "https://350org.zoom.us/j/3411071981",
    "timezone": "Europe/Berlin",
    "verified": 1,
    "dept": "Webinar Account",
    "created_at": "2020-01-30T17:54:20Z",
    "last_login_time": "2020-05-07T11:11:28Z",
    "last_client_version": "4.6.20041.0408(mac)",
    "pic_url": "https://lh5.googleusercontent.com/-RcswbVjzQog/AAAAAAAAAAI/AAAAAAAAAAA/ACHi3reqQ8zTKwdHzTgQugPVpWYdV7XaCg/photo.jpg",
    "host_key": "821200",
    "jid": "6hnrlexjqcisy1izvwl8ea@xmpp.zoom.us",
    "group_ids": [],
    "im_group_ids": [],
    "account_id": "R15o7-M4RO6l3yNf2Jp0rw",
    "language": "en-US",
    "phone_country": "",
    "phone_number": "",
    "status": "active",
    "job_title": "",
    "location": ""
  }

  // dev-team
  {
    "id": "KND-Y6W7Tm2hAia6LyoO8Q",
    "first_name": "",
    "last_name": "",
    "email": "dev-team@350.org",
    "type": 1,
    "role_name": "Member",
    "pmi": 0,
    "use_pmi": false,
    "personal_meeting_url": "",
    "timezone": "",
    "verified": 0,
    "dept": "Product",
    "created_at": "2020-04-30T19:27:14Z",
    "host_key": "582778",
    "jid": "",
    "group_ids": [
      "NhyFRzW_R1uSl7Gm12fH2g"
    ],
    "im_group_ids": [],
    "account_id": "R15o7-M4RO6l3yNf2Jp0rw",
    "language": "",
    "phone_country": "",
    "phone_number": "",
    "status": "active",
    "job_title": "",
    "location": ""
  }