name: Deploy AK Develop
on:
  push:
    branches:
      - new-pipeline
jobs:
    upload-and-notify:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Post to a Slack channel
              id: slack
              uses: slackapi/slack-github-action@v1.25.0
              with:
                # Slack channel id, channel name, or user id to post message.
                # See also: https://api.slack.com/methods/chat.postMessage#channels
                channel-id: 'CHZ9289JR'
                    # For posting a rich message using Block Kit
                payload: |
                    {
                        "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url }}",
                        "blocks": [
                        {
                            "type": "section",
                            "text": {
                            "type": "mrkdwn",
                            "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                            }
                        }
                        ]
                    }
              env:
                SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}