name: Deploy AK Develop
on:
  push:
    branches:
      - new-pipeline
jobs:
    upload-and-notify:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Get first line of commit message
              id: commit_message
              run: |
                echo "COMMIT_MESSAGE_FIRST_LINE=$(git log -1 --pretty=%B | head -n 1)" >> $GITHUB_ENV
                echo "::set-output name=first_line::$(git log -1 --pretty=%B | head -n 1)"

            - name: Post to a Slack channel
              id: slack
              uses: slackapi/slack-github-action@v1.25.0
              with:
                # Slack channel id, channel name, or user id to post message.
                # See also: https://api.slack.com/methods/chat.postMessage#channels
                channel-id: 'CHZ9289JR'
                    # For posting a rich message using Block Kit
                payload: |
                    {
                        "text": "*${{ github.repository }}* has been deployed by ${{ github.event.commit.committer.name }}! :tada: :rocket: :tada: \n",
                        "blocks": [
                        {
                            "type": "section",
                            "text": {
                            "type": "mrkdwn",
                            "text": "*Deployment result* \n ${{ job.status }}"
                            }
                        },
                        {
                            "type": "section",
                            "text": {
                            "type": "mrkdwn",
                            "text": "*Commit* \n ['${{ steps.commit_message.outputs.first_line }}'](https://github.com/${{ github.repository }}/commit/${{ github.sha }})"
                            }
                        }
                        ]
                    }
              env:
                SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}