name: "Deploy Master Assets"

on:
  push:
    branches:
      - new-pipeline

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload 'assets/' to S3 with Public Access
        run: |
          aws s3 sync assets/ s3://s3.350.org/ak/ --acl public-read

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E1A2162YKWCD00 \
            --paths "/*"

  notify_success:
    needs: deploy
    if: ${{ needs.deploy.result == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack notification on success
        uses: 8398a7/action-slack@v3
        with:
          status: success
          fields: repo,commit,author,action
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  notify_failure:
    needs: deploy
    if: ${{ needs.deploy.result == 'failure' }}
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack notification on failure
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          fields: repo,commit,author,action
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}